logging:
  level:
    org.springframework.security: INFO
    
eureka:
  instance:
    prefer-ip-address: true #registry service to eureka with real ip
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  rabbitmq:
    host: 192.168.42.53
    port: 5672
    username: admin
    password: 123456      
