env:
  dev
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?generateSimpleParameterMetadata=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 111
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    hostname: 127.0.0.1
#Load balancing strategy when request PRODUCT-SERVICE server
PRODUCT-SERVICE:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#customized properties
com:
  daniel:
    name: Daniel
    age: 28
label: 
  master
